-- MySQL Script generated by MySQL Workbench
-- Wed Mar 27 21:38:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DW_PMData
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DW_PMData
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DW_PMData` DEFAULT CHARACTER SET utf8 ;
USE `DW_PMData` ;

-- -----------------------------------------------------
-- Table `DW_PMData`.`participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`participant` (
  `participant_id` INT NOT NULL AUTO_INCREMENT,
  `code` INT NULL,
  `age` INT NULL,
  `height` FLOAT NULL,
  `gender` VARCHAR(20) NULL,
  `group` VARCHAR(1) NULL,
  PRIMARY KEY (`participant_id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`injury`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`injury` (
  `injury_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NULL,
  `level` VARCHAR(20) NULL,
  PRIMARY KEY (`injury_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`date` (
  `day_id` INT NOT NULL AUTO_INCREMENT,
  `day` INT NULL,
  `month_id` INT NULL,
  `month` INT NULL,
  `month_name` INT NULL,
  `year_id` INT NULL,
  `year` INT NULL,
  PRIMARY KEY (`day_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`meal` (
  `meal_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NULL,
  PRIMARY KEY (`meal_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`meal_bridge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`meal_bridge` (
  `meal_bridge_id` INT NOT NULL,
  `meal_id` INT NOT NULL,
  PRIMARY KEY (`meal_bridge_id`, `meal_id`),
  INDEX `fk_meals_bridge_meal_idx` (`meal_id` ASC) VISIBLE,
  CONSTRAINT `fk_meals_bridge_meal`
    FOREIGN KEY (`meal_id`)
    REFERENCES `DW_PMData`.`meal` (`meal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`injury_bridge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`injury_bridge` (
  `injury_bridge_id` INT NOT NULL,
  `injury_id` INT NOT NULL,
  PRIMARY KEY (`injury_bridge_id`, `injury_id`),
  INDEX `fk_injury_bridge_injury_idx` (`injury_id` ASC) VISIBLE,
  CONSTRAINT `fk_injury_bridge_injury`
    FOREIGN KEY (`injury_id`)
    REFERENCES `DW_PMData`.`injury` (`injury_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`daily`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`daily` (
  `participant_id` INT NOT NULL,
  `day_id` INT NOT NULL,
  `meal_bridge_id` INT NOT NULL,
  `injury_bridge_id` INT NOT NULL,
  `sedentary_minutes` INT NULL,
  `light_active_minutes` VARCHAR(45) NULL,
  `mod_active_minutes` VARCHAR(45) NULL,
  `very_active_minutes` VARCHAR(45) NULL,
  `fluid_glasses` VARCHAR(45) NULL,
  `weight` FLOAT NULL,
  `steps` INT NULL,
  `calories` FLOAT NULL,
  `consumed_alcohol` TINYINT NULL,
  INDEX `fk_daily_participant_idx` (`participant_id` ASC) VISIBLE,
  PRIMARY KEY (`participant_id`, `day_id`),
  INDEX `fk_daily_meal_bridge_idx` (`meal_bridge_id` ASC) VISIBLE,
  INDEX `fk_daily_injury_bridge_idx` (`injury_bridge_id` ASC) VISIBLE,
  INDEX `fk_daily_date_idx` (`day_id` ASC) INVISIBLE,
  CONSTRAINT `fk_daily_participant`
    FOREIGN KEY (`participant_id`)
    REFERENCES `DW_PMData`.`participant` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_daily_meal_bridge`
    FOREIGN KEY (`meal_bridge_id`)
    REFERENCES `DW_PMData`.`meal_bridge` (`meal_bridge_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_daily_injury_bridge`
    FOREIGN KEY (`injury_bridge_id`)
    REFERENCES `DW_PMData`.`injury_bridge` (`injury_bridge_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_daily_date`
    FOREIGN KEY (`day_id`)
    REFERENCES `DW_PMData`.`date` (`day_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`activity` (
  `activity_id` INT NOT NULL AUTO_INCREMENT,
  `code` INT NULL,
  `name` VARCHAR(20) NULL,
  `level` VARCHAR(20) NULL,
  PRIMARY KEY (`activity_id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`heart_rate_zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`heart_rate_zone` (
  `heart_rate_zone_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  PRIMARY KEY (`heart_rate_zone_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`sleep_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`sleep_type` (
  `sleep_type_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `level` VARCHAR(20) NULL,
  PRIMARY KEY (`sleep_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`sleep_bridge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`sleep_bridge` (
  `sleep_bridge_id` INT NOT NULL,
  `sleep_type_id` INT NOT NULL,
  `weight` FLOAT NULL,
  INDEX `fk_sleep_bridge_sleep_type_idx` (`sleep_type_id` ASC) VISIBLE,
  PRIMARY KEY (`sleep_bridge_id`, `sleep_type_id`),
  CONSTRAINT `fk_sleep_bridge_sleep_type`
    FOREIGN KEY (`sleep_type_id`)
    REFERENCES `DW_PMData`.`sleep_type` (`sleep_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`instant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`instant` (
  `minute_id` INT NOT NULL AUTO_INCREMENT,
  `minute` INT NULL,
  `hour_id` INT NULL,
  `hour` INT NULL,
  `period` VARCHAR(20) NULL,
  PRIMARY KEY (`minute_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`sleep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`sleep` (
  `participant_id` INT NOT NULL,
  `minute_id` INT NOT NULL,
  `day_id` INT NOT NULL,
  `sleep_bridge_id` INT NOT NULL,
  `duration` INT NULL,
  `min_to_fall_a_sleep` INT NULL,
  `min_awake` INT NULL,
  `min_asleep` INT NULL,
  `efficiency` INT NULL,
  `is_main` TINYINT NULL,
  INDEX `fk_sleep_participant_idx` (`participant_id` ASC) VISIBLE,
  PRIMARY KEY (`participant_id`, `minute_id`, `day_id`, `sleep_bridge_id`),
  INDEX `fk_sleep_sleep_bridge_idx` (`sleep_bridge_id` ASC) VISIBLE,
  INDEX `fk_sleep_instant_idx` (`minute_id` ASC) VISIBLE,
  INDEX `fk_sleep_date_idx` (`day_id` ASC) VISIBLE,
  CONSTRAINT `fk_sleep_participant`
    FOREIGN KEY (`participant_id`)
    REFERENCES `DW_PMData`.`participant` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sleep_sleep_bridge`
    FOREIGN KEY (`sleep_bridge_id`)
    REFERENCES `DW_PMData`.`sleep_bridge` (`sleep_bridge_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sleep_instant`
    FOREIGN KEY (`minute_id`)
    REFERENCES `DW_PMData`.`instant` (`minute_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sleep_date`
    FOREIGN KEY (`day_id`)
    REFERENCES `DW_PMData`.`date` (`day_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`activity_bridge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`activity_bridge` (
  `activity_bridge_id` INT NOT NULL,
  `activity_id` INT NOT NULL,
  `weight` FLOAT NULL,
  PRIMARY KEY (`activity_bridge_id`, `activity_id`),
  INDEX `fk_activity_bridge_activity_idx` (`activity_id` ASC) VISIBLE,
  CONSTRAINT `fk_activity_bridge_activity`
    FOREIGN KEY (`activity_id`)
    REFERENCES `DW_PMData`.`activity` (`activity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`heart_rate_zone_bridge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`heart_rate_zone_bridge` (
  `heart_rate_zone_bridge_id` INT NOT NULL,
  `heart_rate_zone_id` INT NOT NULL,
  `weight` FLOAT NULL,
  PRIMARY KEY (`heart_rate_zone_bridge_id`, `heart_rate_zone_id`),
  INDEX `fk_heart_rate_zone_bridge_heart_rate_zone_idx` (`heart_rate_zone_id` ASC) VISIBLE,
  CONSTRAINT `fk_heart_rate_zone_bridge_heart_rate_zone`
    FOREIGN KEY (`heart_rate_zone_id`)
    REFERENCES `DW_PMData`.`heart_rate_zone` (`heart_rate_zone_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DW_PMData`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DW_PMData`.`exercise` (
  `participant_id` INT NOT NULL,
  `heart_rate_zone_bridge_id` INT NOT NULL,
  `day_id` INT NOT NULL,
  `minute_id` INT NOT NULL,
  `activity_bridge_id` INT NOT NULL,
  `duration` INT NULL,
  `calories` FLOAT NULL,
  `steps` INT NULL,
  `elevation_gain` FLOAT NULL,
  `avg_heart_rate` FLOAT NULL,
  `heart_rate_during_exercise` JSON NULL,
  `activity_type` VARCHAR(45) NULL,
  `with_team` TINYINT NULL,
  INDEX `fk_exercise_participant_idx` (`participant_id` ASC) VISIBLE,
  PRIMARY KEY (`participant_id`, `heart_rate_zone_bridge_id`, `day_id`, `minute_id`, `activity_bridge_id`),
  INDEX `fk_exercise_activity_bridge_idx` (`activity_bridge_id` ASC) VISIBLE,
  INDEX `fk_exercise_heart_rate_zone_bridge_idx` (`heart_rate_zone_bridge_id` ASC) VISIBLE,
  INDEX `fk_exercise_instant_idx` (`minute_id` ASC) VISIBLE,
  INDEX `fk_exercise_date_idx` (`day_id` ASC) VISIBLE,
  CONSTRAINT `fk_exercise_participant`
    FOREIGN KEY (`participant_id`)
    REFERENCES `DW_PMData`.`participant` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercise_activity_bridge`
    FOREIGN KEY (`activity_bridge_id`)
    REFERENCES `DW_PMData`.`activity_bridge` (`activity_bridge_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercise_heart_rate_zone_bridge`
    FOREIGN KEY (`heart_rate_zone_bridge_id`)
    REFERENCES `DW_PMData`.`heart_rate_zone_bridge` (`heart_rate_zone_bridge_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercise_instant`
    FOREIGN KEY (`minute_id`)
    REFERENCES `DW_PMData`.`instant` (`minute_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercise_date`
    FOREIGN KEY (`day_id`)
    REFERENCES `DW_PMData`.`date` (`day_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
